### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Kimsure** [nhw649/EOV-Seg#1]
Thanks for your impressive work and congrats to be accepted!
I have some questions:
1. This code introduce the whole vit-b CLIP into the model ? Taking the first layer or the last layer demands the same parameter?
2. How to reproduce the Fig.3? Is it the k-means result from the VFM feature map? Is it the same if using the text-image similarity map?

**Comment by nhw649** [comment]
> Thanks for your impressive work and congrats to be accepted! I have some questions:
> 
> 1. This code introduce the whole vit-b CLIP into the model ? Taking the first layer or the last layer demands the same parameter?
> 2. How to reproduce the Fig.3? Is it the k-means result from the VFM feature map? Is it the same if using the text-image similarity map?

Thank you for your interest in our research.

1. Although we load the entire ViT-B model, we only use the first block, [this](https://github.com/nhw649/EOV-Seg/blob/6f5e93e9aca6ccae89fe492b24018f8530075fc4/eov_seg/modeling/backbone/clip.py#L239).
2. You only need to perform K-means on the feature maps extracted by different VFM pre-trained backbones. The effect of the text-image similarity map can be referred to [CLIP Surgery](https://github.com/xmed-lab/CLIP_Surgery).

We hope these answers are helpful to you. Thank you very much.

**Comment by Kimsure** [comment]
Understood. Thanks for your reply
