### ISSUE TITLE
unable to get the .pt file.

### ISSUE THREAD

**Issue by jkff00** [nhw649/EOV-Seg#2]
Hi authors,

Thank you for your excellent work! I got a bit of difficulties of running it.
1. the model weights file seems to require authorisation, if you notice.
2. also, may I ask if the pixel-aligned semantic features embedding  the context info.

Thanks!

**Comment by nhw649** [comment]
Thank you for your interest in our research.
1. I have modified the permissions. You can try to download again.
2. Yes, as you said.

**Comment by nhw649** [comment]
> Hi authors,
> 
> Thank you for your excellent work! I got a bit of difficulties of running it.
> 
> 1. the model weights file seems to require authorisation, if you notice.
> 2. also, may I ask if the pixel-aligned semantic features embedding  the context info.
> 
> Thanks!

Thank you for your interest in our research.
1. I have modified the permissions. You can try to download again.
2. Yes, as you said.

**Comment by jkff00** [comment]
Thanks for your reply!

**Comment by jkff00** [comment]
After configuring the environment according to the process, I ran demo.py with the following error, KeyError: ‘No object named “build_resnet_backbone” found in “BACKBONE” registry!’

This seems to be because detectron2 is not loaded, can you give me some suggestions?

**Comment by jkff00** [comment]
For what it's worth, I installed detectron2 using the following command: python -m pip install ‘git+https://github.com/facebookresearch/detectron2.git’. This is because cloning the repository first and then installing it locally results in an error: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory.

**Comment by nhw649** [comment]
> For what it's worth, I installed detectron2 using the following command: python -m pip install ‘git+[https://github.com/facebookresearch/detectron2.git’](https://github.com/facebookresearch/detectron2.git%E2%80%99). This is because cloning the repository first and then installing it locally results in an error: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory.

Please install the torch version (torch>=1.13.0) based on your CUDA version.

**Comment by jkff00** [comment]
My torch version is 2.4.1+cu118.

**Comment by nhw649** [comment]
> My torch version is 2.4.1+cu118.

Please follow the provided configuration to install.

**Comment by jkff00** [comment]
I reconfigured the environment, currently torch=1.13, cuda=11.7,but the problem is still not solved. I found that the dictionary is empty by applying ‘print(’Available backbones:‘, BACKBONE_REGISTRY._obj_map.keys())’ in the build.py file, is there any problem with this.

Traceback (most recent call last):
  File "demo/demo.py", line 136, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/xf/EOV-Seg/demo/predictor.py", line 150, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/xf/detectron2/detectron2/engine/defaults.py", line 314, in __init__
    self.model = build_model(self.cfg)
  File "/home/xf/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/xf/EOV-Seg/demo/../eov_seg/modeling/meta_arch/segmentator.py", line 52, in __init__
    self.cnn_backbone = build_backbone(cfg, backbone_type="cnn")
  File "/home/xf/EOV-Seg/demo/../eov_seg/modeling/backbone/build.py", line 33, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape, backbone_type)
  File "/home/xf/.conda/envs/eov-seg/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'build_resnet_backbone' found in 'BACKBONE' registry!"

**Comment by jkff00** [comment]
I think it's because I chose the wrong config file, I chose eov_seg/eov_seg_R50.yaml and it's fine!

**Comment by jkff00** [comment]
Run the command: "python demo/demo.py --config-file configs/eov_seg/eov_seg_convnext_l.yaml --input input/ --output output/ --opts MODEL.WEIGHTS weight/convnext-l.pth" directly and get the following error: "RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (128, 128)."
