### ISSUE TITLE
Inference time lower than 10 FPS.

### ISSUE THREAD

**Issue by jkff00** [nhw649/EOV-Seg#3]
I run python demo/demo.py on 4060 GPU with --config-file configs/eov_seg/eov_seg_convnext_l.yaml --input input/ --output output/ --opts MODEL.WEIGHTS weight/convnext-l.pth, prediction on input views, demo.run_on_image(img) took at ~ 3FPS, image size is (680, 1200). In addition it needs about 100s of initialisation. Is there a way to optimise it?

Also, self.predictor(image) seems to only return the mask id and the corresponding label id, how to get the semantic embedding vector for each mask. It is worth noting that the prediction results are not fully pixel segmented (e.g. the trash can), for what reason? Thanks for your reply.
![0](https://github.com/user-attachments/assets/1e50c3c6-1a33-4e59-a7aa-26fc22b97f12)
![0](https://github.com/user-attachments/assets/6c5fbe7b-4b11-4f77-b6ad-bb3211983d72)

**Comment by nhw649** [comment]
1. The calculation of inference time does not include the time of image preprocessing and result post-processing.
2. The model does not predict perfectly, and improving its performance is a current research focus.
